/**
 * Virtual modules generated by `defineWalleConfig` (src/@walle/define-config.ts).
 * Declared here so consumers get types without depending on how they are produced.
 */
declare module "virtual:walle-pwa" {
  const pwa: {
    enabled: boolean;
    manifestHref?: string;
    registerHref?: string;
    themeColor?: string | null;
    appleTouchIcon?: string | null;
  };
  export default pwa;
}

/**
 * Commerce UI gated at the module-graph level (D10): `null` when `commerce.mode !== "shop"`,
 * so a vetrina site's build never even emits a chunk for the cart components.
 */
declare module "virtual:walle-features" {
  export const CartMount: typeof import("./commerce/CartMount.astro").default | null;
  export const CartBadge: typeof import("./commerce/CartBadge.astro").default | null;
}

/**
 * One entry per configured `typography.fonts` (D11): what Head.astro needs to render one
 * `<Font cssVariable preload />` per font — everything else (name, provider, weights...) is
 * only relevant to Astro's own build-time `fonts` config, resolved in define-config.ts.
 */
declare module "virtual:walle-fonts" {
  export const fonts: Array<{ cssVariable: string; preload: boolean }>;
}

/**
 * One export per embeddable component (D6), each typed against its own "standard" walle
 * implementation. A site override must accept the same props and slots to be a valid
 * replacement, so this is the contract a `components.<key>` path is held to.
 */
declare module "virtual:walle-components" {
  export const navbar: typeof import("./components/features/Navbar/Navbar.astro").default;
  export const footer: typeof import("./components/features/Footer.astro").default;
  export const card: typeof import("./components/features/Card/BasicCard.astro").default;
  export const breadcrumbs: typeof import("./components/features/Breadcrumbs.astro").default;
  export const pageHeader: typeof import("./components/features/Sections/HeaderStandard.astro").default;
  export const toc: typeof import("./components/features/Blog/BlogTableOfContents.astro").default;
}
