/**
 * Virtual modules generated by `defineWalleConfig` (src/@walle/define-config.ts).
 * Declared here so consumers get types without depending on how they are produced.
 */
declare module "virtual:walle-pwa" {
  const pwa: {
    enabled: boolean;
    manifestHref?: string;
    registerHref?: string;
    themeColor?: string | null;
    appleTouchIcon?: string | null;
  };
  export default pwa;
}
