// Single source of truth for the shape of src/configs/{app,navbar,footer,theme}.json.
// These zod schemas replace the hand-written interfaces (config/index.ts) and the
// hand-maintained JSON Schemas (schemas/*.schema.json, regenerated by
// walle/cli/generate-schemas.mjs). Parsing happens in define-config.ts (build time) and
// config/index.ts (runtime), both of which throw on a mismatch instead of silently
// accepting an invalid config.
import { z } from "astro/zod";

// Re-exported so walle/cli/generate-schemas.mjs (outside this package's node_modules
// resolution scope) can reach `z.toJSONSchema`/`z.prettifyError` through this file's own
// import instead of importing "astro/zod" directly from a location where it wouldn't resolve.
export { z };

/**
 * Declares a key that used to be valid and no longer is. The key stays a known property
 * (so `.strict()` reports the guidance message below instead of a generic "unrecognized
 * key" error) but only ever validates when absent.
 */
function removedKey(guidance: string) {
  return z
    .unknown()
    .optional()
    .refine((value) => value === undefined, {
      message: `This key has been removed. Use "${guidance}" instead.`,
    });
}

const logoSchema = z
  .object({
    src: z.string().optional(),
    title: z.string().optional(),
    url: z.string(),
    width: z.number().optional(),
    height: z.number().optional(),
    alt: z.string().optional(),
    cssClasses: z.string().optional(),
    license: z.string().optional(),
  })
  .strict();

const navigationTarget = z.enum(["_blank", "_self"]);

const dropdownLinkSchema = z
  .object({
    name: z.string().optional(),
    url: z.string(),
    icon: z.string().optional(),
    target: navigationTarget.optional(),
  })
  .strict();

const navigationLinkSchema = z
  .object({
    name: z.string().optional(),
    url: z.string(),
    icon: z.string().optional(),
    target: navigationTarget.optional(),
    dropdown: z.array(dropdownLinkSchema).optional(),
  })
  .strict();

// Footer links don't support a dropdown (matches today's footer.schema.json definitions.navigationLink).
const footerLinkSchema = z
  .object({
    name: z.string().optional(),
    url: z.string(),
    icon: z.string().optional(),
    target: navigationTarget.optional(),
  })
  .strict();

export const navbarSchema = z
  .object({
    $schema: z.string().optional(),
    logo: logoSchema,
    items: z.array(navigationLinkSchema),
  })
  .strict();

export const footerSchema = z
  .object({
    $schema: z.string().optional(),
    logo: logoSchema,
    items: z.array(footerLinkSchema),
  })
  .strict();

const websiteSchema = z
  .object({
    title: z.string(),
    description: z.string(),
    favicon: z.string().optional(),
    image: z.string().optional(),
    robots: z.string().optional(),
    language: z.string().optional(),
    titleMaxLength: z.number().int().min(20).optional(),
    descriptionMaxLength: z.number().int().min(50).optional(),
  })
  .strict();

const astroSchema = z
  .object({
    baseUrl: z.string(),
    basePath: z.string(),
    trailingSlash: z.enum(["always", "never", "ignore"]).optional(),
    analyticsScriptContent: z.string().optional(),
    sitemapExclude: z.array(z.string()).optional(),
    // Passed straight through to Astro's native `redirects` config; its own static-output
    // redirect page already emits refresh/noindex/canonical, so walle only adds the sitemap
    // exclusion (D9) — the redirect source is never listed alongside the destination.
    redirects: z
      .record(
        z.string(),
        z.union([
          z.string(),
          z
            .object({
              destination: z.string(),
              status: z.union([z.literal(301), z.literal(302), z.literal(307), z.literal(308)]),
            })
            .strict(),
        ])
      )
      .optional(),
    // Replaces the old `astro.ssr` shape: a single string toggle rather than a nested
    // { enabled, adapter } object. Adds the node adapter with `output` left at Astro's
    // default ("static"), so only routes that declare `prerender = false` render on demand.
    adapter: z.enum(["node"]).optional(),
    ssr: removedKey("astro.adapter"),
    // Astro's own `prefetch` is opt-in and off by default; walle defaults it ON with the
    // hover strategy (D9) — `false` opts a site out entirely. `strategy`/`all` are walle's
    // own friendlier names for Astro's `defaultStrategy`/`prefetchAll`.
    prefetch: z
      .union([
        z.literal(false),
        z
          .object({
            strategy: z.enum(["hover", "tap", "viewport", "load"]).optional(),
            all: z.boolean().optional(),
          })
          .strict(),
      ])
      .optional(),
  })
  .strict();

const pwaIconSchema = z
  .object({
    src: z.string(),
    sizes: z.string(),
    type: z.string().optional(),
    purpose: z.string().optional(),
  })
  .strict();

const pwaSchema = z
  .object({
    enabled: z.boolean().optional(),
    name: z.string().optional(),
    shortName: z.string().optional(),
    description: z.string().optional(),
    lang: z.string().optional(),
    themeColor: z.string().optional(),
    backgroundColor: z.string().optional(),
    display: z.enum(["standalone", "fullscreen", "minimal-ui", "browser"]).optional(),
    startUrl: z.string().optional(),
    scope: z.string().optional(),
    icons: z.array(pwaIconSchema).optional(),
    appleTouchIcon: z.string().optional(),
  })
  .strict();

const commerceSchema = z
  .object({
    // Off by default: no cart UI, no /products gating. "catalog" shows products with no
    // buy controls (vetrina); "shop" is the full cart + checkout flow.
    mode: z.enum(["off", "catalog", "shop"]).default("off"),
    cartInNavbar: z.boolean().optional(),
    showAddToCartOnCards: z.boolean().optional(),
    // Replaced by `commerce.mode === "shop"`.
    showBuyButton: removedKey("commerce.mode"),
    // Replaced by `website.language`: one locale for the whole site, not a commerce-only one.
    locale: removedKey("website.language"),
    // Replaced by the `labels` config.
    addToCartLabel: removedKey("labels"),
  })
  .strict();

const breadcrumbsLabelsSchema = z
  .object({ nav: z.string().optional(), back: z.string().optional() })
  .strict();

const carouselLabelsSchema = z
  .object({
    previous: z.string().optional(),
    next: z.string().optional(),
    zoom: z.string().optional(),
    close: z.string().optional(),
    slide: z.string().optional(),
  })
  .strict();

const filtersLabelsSchema = z
  .object({
    searchPlaceholder: z.string().optional(),
    searchLabel: z.string().optional(),
    clear: z.string().optional(),
    status: z.string().optional(),
    facetSelect: z.string().optional(),
    facetSelected: z.string().optional(),
  })
  .strict();

const cartLabelsSchema = z
  .object({
    ariaLabel: z.string().optional(),
    open: z.string().optional(),
    title: z.string().optional(),
    close: z.string().optional(),
    empty: z.string().optional(),
    subtotal: z.string().optional(),
    checkout: z.string().optional(),
    add: z.string().optional(),
    decreaseQuantity: z.string().optional(),
    increaseQuantity: z.string().optional(),
    remove: z.string().optional(),
    inStock: z.string().optional(),
    outOfStock: z.string().optional(),
    unavailable: z.string().optional(),
  })
  .strict();

const priceLabelsSchema = z
  .object({
    discounted: z.string().optional(),
    original: z.string().optional(),
  })
  .strict();

const offlineLabelsSchema = z
  .object({
    title: z.string().optional(),
    message: z.string().optional(),
  })
  .strict();

const notFoundLabelsSchema = z
  .object({
    title: z.string().optional(),
    message: z.string().optional(),
  })
  .strict();

const tocLabelsSchema = z
  .object({
    heading: z.string().optional(),
    nav: z.string().optional(),
    loading: z.string().optional(),
    expanded: z.string().optional(),
    collapsed: z.string().optional(),
  })
  .strict();

const navLabelsSchema = z
  .object({
    main: z.string().optional(),
    toggle: z.string().optional(),
  })
  .strict();

const footerLabelsSchema = z
  .object({
    nav: z.string().optional(),
    social: z.string().optional(),
  })
  .strict();

const blogLabelsSchema = z
  .object({
    readingProgress: z.string().optional(),
    articleNavigation: z.string().optional(),
    previousArticle: z.string().optional(),
    nextArticle: z.string().optional(),
    info: z.string().optional(),
    tags: z.string().optional(),
    empty: z.string().optional(),
  })
  .strict();

// Every user-facing/screen-reader string walle emits, grouped by area (D8). Each leaf has an
// English default in i18n.ts; a component prop for the same label overrides the site value.
const labelsSchema = z
  .object({
    skipLink: z.string().optional(),
    breadcrumbs: breadcrumbsLabelsSchema.optional(),
    carousel: carouselLabelsSchema.optional(),
    filters: filtersLabelsSchema.optional(),
    cart: cartLabelsSchema.optional(),
    price: priceLabelsSchema.optional(),
    offline: offlineLabelsSchema.optional(),
    notFound: notFoundLabelsSchema.optional(),
    toc: tocLabelsSchema.optional(),
    readingTime: z.string().optional(),
    nav: navLabelsSchema.optional(),
    footer: footerLabelsSchema.optional(),
    blog: blogLabelsSchema.optional(),
  })
  .strict();

export const appSchema = z
  .object({
    $schema: z.string().optional(),
    website: websiteSchema,
    astro: astroSchema,
    components: z.record(z.string(), z.string()).optional(),
    pwa: pwaSchema.optional(),
    commerce: commerceSchema.optional(),
    labels: labelsSchema.optional(),
  })
  .strict();

const themePaletteSchema = z.record(z.string(), z.string()).optional();
const themeScaleSchema = z.record(z.string(), z.string()).optional();

const themeTypographySchema = z
  .object({
    fontFamilyBase: z.string().optional(),
    fontFamilyHeading: z.string().optional(),
    fontFamilyMono: z.string().optional(),
    scale: themeScaleSchema,
  })
  .strict();

export const themeSchema = z
  .object({
    $schema: z.string().optional(),
    palette: themePaletteSchema,
    typography: themeTypographySchema.optional(),
    spacing: z.record(z.string(), z.string()).optional(),
    radii: z.record(z.string(), z.string()).optional(),
    neutral: z.record(z.string(), z.string()).optional(),
    shadow: z.record(z.string(), z.string()).optional(),
  })
  .strict();

export type AppConfig = z.infer<typeof appSchema>;
export type NavbarConfig = z.infer<typeof navbarSchema>;
export type FooterConfig = z.infer<typeof footerSchema>;
export type ThemeConfig = z.infer<typeof themeSchema>;
export type NavigationLink = z.infer<typeof navigationLinkSchema>;
export type NavbarLogo = z.infer<typeof logoSchema>;
export type LabelsConfig = z.infer<typeof labelsSchema>;

/** Parses `data` against `schema`, throwing a `z.prettifyError` message prefixed with `fileName`. */
export function parseConfig<T>(schema: z.ZodType<T>, data: unknown, fileName: string): T {
  const result = schema.safeParse(data);
  if (!result.success) {
    throw new Error(`Invalid walle config in ${fileName}:\n${z.prettifyError(result.error)}`);
  }
  return result.data;
}
